repr methods of linter.py now returns memory location.
coala/coala pull request #6149
Opened 2021-03-15 18:11 UTC by anshalshukla

`repr` methods in linter.py now returns memory location. Tests have been modified and successfully tested with 100% coverage.
closes #6051

2021-03-25 15:22 UTC, abhishalya commented
Commit guidelines are not followed here. Also for a set of changes belonging to same issue, they should have a single commit.

2021-03-25 16:22 UTC, anshalshukla commented
@abhishalya Is it fine now?

2021-03-25 16:28 UTC, abhishalya requested changes

2021-03-25 16:28 UTC, abhishalya commented on tests/bearlib/abstractions/LinterTest.py
> +        # Start ignoring LineLengthBear, PycodestyleBear
No, you should try to stick to existing limit. Use of these is discouraged.

2021-03-25 16:28 UTC, abhishalya commented on tests/settings/ConfigurationGatheringTest.py
> +        # Start ignoring LineLengthBear, PycodestyleBear
You have overused it. Please remove these.

2021-03-25 17:09 UTC, anshalshukla commented
I have done the suggested changes.

2021-03-26 17:16 UTC, abhishalya approved these changes
LGTM :tada:

2021-03-27 03:36 UTC, merged