Athirai
coala/coala pull request #6157
Opened 2021-03-25 04:56 UTC by athirai-s

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

2021-03-25 15:23 UTC, abhishalya commented
Please squash the commits into a single commit. Also the PR title seems to be off.

2021-03-25 15:57 UTC, athirai-s commented
Done!

2021-03-25 16:01 UTC, abhishalya commented
Well you added a new commit and now it has conflicts too. I just want a single commit.

2021-03-26 17:09 UTC, abhishalya commented
This does not look good, please ask for help on gitter if you need help using git :)

2021-05-07 07:01 UTC, utkarsh2102 requested changes

2021-05-07 07:01 UTC, utkarsh2102 commented on docs/Developers/Git_Basics.rst
>  the desired branch:
Actually, you're editing the very doc that you need to use 😄 
Maybe follow this very doc and see if you can come up with something?
`git rebase -i [...]` is your friend, let me know if you need help!

2021-05-14 15:17 UTC, abhishalya commented
Closing as the PR was abandoned with invalid changes.

2021-05-14 15:17 UTC, closed without merging